#!/usr/bin/env python3
"""Maintainer tool: write the generated documents.

- architecture-diagrams/references/symbols.md from the symbol, icon and stencil sources;
- PROMPT.md, the prompt for any chat AI (the same text as the editor's "Copy prompt for AI").

Run it after adding or changing a symbol, an icon, a stencil library or assets/ai-prompt.md:
    python3 tools/make_docs.py            (python3 tools/make_docs.py --check only compares)
tests/test_docs.py fails when a generated file is out of date.
"""

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / "architecture-diagrams"
OUT = SKILL / "references" / "symbols.md"
PROMPT_OUT = ROOT / "PROMPT.md"
sys.dont_write_bytecode = True
sys.path.insert(0, str(SKILL / "scripts"))
from build import ai_prompt  # noqa: E402

PROMPT_HEAD = """# Prompt for any AI chat

Paste everything below the line into ChatGPT, Gemini, Copilot, Claude or any other chat and write your request at the end, for example "Draw the clock and reset tree of our SoC: ...". Save the JSON it returns as `diagram.json` and run `python3 architecture-diagrams/scripts/build.py diagram.json`, or paste it into the JSON tab of any page built by this tool (for example `docs/editor.html`) and press Apply.

*Tiếng Việt: dán toàn bộ phần dưới vạch vào khung chat của AI bất kỳ rồi gõ yêu cầu vào cuối. Lưu JSON mà AI trả về thành file `diagram.json` rồi chạy lệnh dựng trang như trên, hoặc dán vào tab JSON của trình sửa rồi bấm Áp dụng. Nút "Chép prompt cho AI" trong trình sửa chép đúng nội dung này, kèm sơ đồ đang mở.*

Generated by `tools/make_docs.py` from `architecture-diagrams/assets/ai-prompt.md` and the symbol list; do not edit by hand.

---

"""


def prompt_doc():
    return PROMPT_HEAD + ai_prompt().rstrip("\n") + "\n\nRequest: \n"

CATS = [("basic", "Basic shapes and flowchart"), ("logic", "Logic gates"), ("digital", "Digital blocks"),
        ("analog", "Analog and mixed-signal"), ("passive", "Passives and transistors"), ("software", "Software and IT")]
DIRS = {"in": "in", "out": "out", "clk": "clock/enable (required once wired)", "io": "no direction"}


def load():
    src = (SKILL / "assets" / "js" / "symbols.js").read_text(encoding="utf-8")
    body = src[src.index("var SYMBOLS = {"):src.index("var SYMBOL_ALIAS")]
    alias_src = src[src.index("var SYMBOL_ALIAS = {"):src.index("var SYMBOL_CATS")]
    aliases = {}
    for alias, name in re.findall(r"'?([a-z0-9-]+)'?: '([a-z0-9-]+)'", alias_src):
        aliases.setdefault(name, []).append(alias)
    symbols = []
    for m in re.finditer(r"^  '?([a-z][a-z0-9-]*)'?: \{ cat: '(\w+)'(.*)$", body, re.M):
        name, cat, rest = m.group(1), m.group(2), m.group(3)
        size = re.search(r"size: \[(\d+(?:\.\d+)?), (\d+(?:\.\d+)?)\]", rest)
        pins = re.search(r"pins: (\[\[.*?\]\])", rest)
        symbols.append({"name": name, "cat": cat, "size": (size.group(1), size.group(2)) if size else None,
                        "pins": json.loads(pins.group(1).replace("'", '"')) if pins else [], "aliases": sorted(aliases.get(name, []))})
    icons_src = (SKILL / "assets" / "js" / "icons.js").read_text(encoding="utf-8")
    groups = json.loads(icons_src[icons_src.index("var ICON_GROUPS = ") + len("var ICON_GROUPS = "):].rstrip().rstrip(";"))
    libs = []
    for path in sorted((SKILL / "assets" / "stencils").glob("*.xml")):
        root = ET.parse(path).getroot()
        names = [s.get("name") for s in root if s.tag == "shape" and s.get("name")]
        libs.append(((root.get("name") or "").lower(), names))
    return symbols, groups, libs


def render():
    symbols, groups, libs = load()
    out = ["# Symbols, pins and icons", "",
           "Generated by `tools/make_symbols_doc.py` from `assets/js/symbols.js`, `assets/js/icons.js` and `assets/stencils/`; do not edit by hand.", "",
           "Use a symbol with `\"shape\": \"<name>\"` (an alias works too). Pins are given as NAME (direction) at [x, y]: x and y are fractions of the block box from its top-left corner, "
           "so `\"toAnchor\": [0, 0.72]` puts a wire end on a flip-flop's CLK pin. Directions: " + ", ".join(f"`{k}` {v}" for k, v in DIRS.items()) + ". "
           "Pins turn and mirror with `style.direction`, `style.flipH` and `style.flipV`.", ""]
    for cat, title in CATS:
        rows = [s for s in symbols if s["cat"] == cat]
        if not rows:
            continue
        out += [f"## {title}", "", "| Symbol | Size | Pins | Also called |", "| --- | --- | --- | --- |"]
        for s in rows:
            pins = ", ".join(f"{p[2]} ({p[3]}) [{p[0]:g}, {p[1]:g}]" for p in s["pins"]) or "none"
            size = f"{float(s['size'][0]):g} × {float(s['size'][1]):g}" if s["size"] else ""
            out.append(f"| `{s['name']}` | {size} | {pins} | {', '.join(s['aliases'])} |")
        out.append("")
    out += ["## Icons", "",
            "Lucide icons (ISC License) for `\"icon\"` on cards and groups, or as a block with `\"shape\": \"icon\"`. Any emoji works as well.", ""]
    for name, items in groups.items():
        out.append(f"- **{name}**: " + ", ".join(items))
    out += ["", "## draw.io libraries", "",
            "Shapes from these draw.io libraries (Apache License 2.0) draw exactly as in draw.io. Use the full name: the library name, a dot, "
            "and the shape name in lower case with spaces as `_`, for example `mxgraph.electrical.logic_gates.and`. Their pin names come from draw.io "
            "(`in1`, `out`, `N`, `E` …); pins named in or out get a direction.", ""]
    for lib, names in libs:
        sample = ", ".join(n.replace(" ", "_").lower() for n in names[:8])
        out.append(f"- `{lib}` ({len(names)} shapes): {sample}{', …' if len(names) > 8 else ''}")
    out.append("")
    return "\n".join(out)


def main(argv):
    outputs = [(OUT, render()), (PROMPT_OUT, prompt_doc())]
    if "--check" in argv:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            print("Out of date: " + ", ".join(stale) + ". Run python3 tools/make_docs.py")
        return 1 if stale else 0
    for path, text in outputs:
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)} ({len(text.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
